# Generated by Django 4.2.6 on 2023-11-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_private_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='approveStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='base.room'),
        ),
    ]
