# Generated by Django 4.2.6 on 2023-12-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_directmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
    ]
